// Generated by CoffeeScript 1.10.0
(function() {
  var AfterBrunch, exec, sysPath;

  sysPath = require('path');

  exec = require('child_process').exec;

  module.exports = AfterBrunch = (function() {
    AfterBrunch.prototype.brunchPlugin = true;

    function AfterBrunch(config) {
      var ref;
      this.config = config;
      this.commands = (ref = this.config.plugins.afterBrunch) != null ? ref : [];
    }

    AfterBrunch.prototype.onCompile = function(generatedFiles) {
      var command, i, len, options, ref;
      ref = this.commands;
      for (i = 0, len = ref.length; i < len; i++) {
        command = ref[i];
        options = {};
        if (command !== null && typeof command === 'object') {
          command = command.command;
        }
        exec(command, options, function(error, stdout, stderr) {
          if (stdout) {
            console.log(stdout);
          }
          if (error) {
            console.log(error.message);
          }
          if (stderr) {
            return console.log(stderr);
          }
        });
      }
    };

    return AfterBrunch;

  })();

}).call(this);
